### ISSUE TITLE
Crash / Bug?

### ISSUE THREAD

**Issue by CriticalComposer** [DeepVoyager253/FlowLauncherYTDownload#1]
I've used this module before without issues but today it's crashing no matter what video I try to download. This happens for both audio and video downloads. Here's the crash log. I tried reinstalling the plug-in and that didn't work. 

I do notice that it's looking in C:\projects\... when that isn't a folder on my system, nor is that folder created when I attempt to download a video. Let me know if you need any more info or if you need me to do/test anything on my end.
```
Flow Launcher version: 1.14.1
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/04/2023 10:02:14
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 96, in <module>
    YoutubeDownload()
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 59, in download_audio
    mp3 = yt_video.streams.filter(only_audio=True).first()
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\[UserName]\Home\FlowLauncher\app-1.14.1\UserData\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 161, in streaming_data
    return self.vid_info['streamingData']
KeyError: 'streamingData'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by eyalBr7** [comment]
on it. should be fixed by the end of the day.
