### ISSUE TITLE
Bug With New Version

### ISSUE THREAD

**Issue by CriticalComposer** [DeepVoyager253/FlowLauncherYTDownload#2]
To preface, the new version that you released today has the same version number in plugin.json so FlowLauncher won't update it. So I uninstalled the plugin and did a clean install of it instead. 

Anywho, the plugin crashes as soon as I use the action word for it. For transparency I'm still using the default -yt but I did try changing it, just in case. I did update to FlowLauncher 1.15 between yesterday and today but otherwise the system is in the same state. This is the new crash log:

```
Flow Launcher version: 1.15.0
OS Version: 19044.2846
IntPtr Length: 8
x64: True

Python Path: C:\Users\[UserName]\Home\FlowLauncher\app-1.15.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: C:\Users\[UserName]\Home\FlowLauncher\app-1.15.0\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/05/2023 09:20:10
Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.ReportWindow.Hyperlink(String textBeforeUrl, String url) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 79
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 53
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 15
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 28
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by eyalBr7** [comment]
This is a known issue, will hopefully be fixed later today. From my testing, this only happens in specific cases, also why I didn't PR flow launcher to queue an update. As I said, I'm on it.

**Comment by heldheld** [comment]
This is still an issue, at least on my end.

**Comment by eyalBr7** [comment]
hello, this is an issue that sometimes occurs when using the flow launcher python environment. i recommend installing python 3.8.9 from this link: https://www.python.org/downloads/release/python-389/ and going to flow launchers settings, then selecting the installation path in the "python path" field. hope this helps.

**Comment by heldheld** [comment]
> 

Unfortunately, this did not help. Same result.

```
Flow Launcher version: 1.15.0
OS Version: 19045.2965
IntPtr Length: 8
x64: True

Python Path: C:\Users\[username]\AppData\Local\Programs\Python\Python38\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 06/02/2023 15:26:41
Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Flow.Launcher.ReportWindow.Hyperlink(String textBeforeUrl, String url) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 79
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 53
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 15
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 28
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by heldheld** [comment]
> hello, this is an issue that sometimes occurs when using the flow launcher python environment. i recommend installing python 3.8.9 from this link: https://www.python.org/downloads/release/python-389/ and going to flow launchers settings, then selecting the installation path in the "python path" field. hope this helps.

So, since your proposed solution did not solve it, is this still treated as an actual issue? I noticed you closed it as completed?

**Comment by eyalBr7** [comment]
it should work now! just try switching back to the flow python installation and reinstalling the plugin by removing it through the gui or command, and redownloading. if you still encounter any error, please let me know. i will not be closing this issue until i get a que from you.

@heldheld @CriticalComposer

**Comment by heldheld** [comment]
> it should work now! just try switching back to the flow python installation and reinstalling the plugin by removing it through the gui or command, and redownloading. if you still encounter any error, please let me know. i will not be closing this issue until i get a que from you.
> 
> @heldheld @CriticalComposer

Thanks for helping! It's not solved yet, but at least I don't get an error right away when I type the Action keyword any more. I do get an error when I give an url and choose either mp3 or mp4.

```
Flow Launcher version: 1.15.0
OS Version: 19045.2965
IntPtr Length: 8
x64: True

Python Path: C:\Users\[user]\AppData\Local\Programs\Python\Python38\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 06/08/2023 21:43:39
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 65, in <module>
    YoutubeDownload()
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 59, in download_video
    video = youtube.streams.filter(progressive=True, file_extension='mp4').first()
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\[user]\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 264, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
pytube.exceptions.AgeRestrictedError: jlcMFoGRzuM is age restricted, and can't be accessed without logging in.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 300
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Btw, I see you've made an 1.0.0-beta, but I can't update to it "Error: A plugin which has the same or greater version with Youtube Downloader already exists."
Removing and re-installing gives me the none beta version.

**Comment by eyalBr7** [comment]
The video you are trying to download is age restricted. That's the error you're getting. 1.0.0 is the intended download version.

**Comment by heldheld** [comment]
> The video you are trying to download is age restricted. That's the error you're getting. 1.0.0 is the intended download version.

Oh lol, it was just a The Office compilation so I didn't really expect that. It works on other video's! This is such a great and easy way to download YouTube video's, I love it :D!

-

Two more questions that arise now that I can use it: I downloaded a 1080p video and the prompt says 'Download your video in full quality', but the downloaded video is in 360p. Is there any way to download a higher resolution?

That same video has 2 audio tracks; an English one and a Spanish one. When I download the video, I get the English one, but when I download the audio I get the Spanish one. Both files only have the one audio track. Is there any way to have some more control over this. Either choosing the audio track or getting them both in the file? (also, the audio option generates a mp4, not a mp3 as the prompt states)

This is the (random) video I was trying it out with: https://www.youtube.com/watch?v=UHc6ESnEztY

**Comment by CriticalComposer** [comment]
This fixed all of the errors with the plugin and it was nice to have it updated through Flow Launcher. I ran into the same issue as Handheld though in that video downloaded in 360p and audio was in the mp4 container.

**Comment by eyalBr7** [comment]
Hey! I fixed the issue with the resolution and the file format. sadly, since pytube (my downloader API) is not well maintained, there's not a lot i can do about the multi-language tracks. in the future, if i decide to change the youtube implementation, I'll keep that feature in mind.

**Comment by heldheld** [comment]
> 

Nice! I see the audio indeed creates a mp3 file now. The video (the same as my previous example) now outputs a 720p file, which is not the 1080p I'd hope, but still a lot better than 360p. I've seen similar behaviour in other YouTube download methods in the past, so I'm not sure if this can be improved?

The multiple audio tracks would be great, but I get that it's a more advanced and more niche feature, thanks for keeping it in mind.
