### ISSUE TITLE
Exception when trying to download mp3 or video

### ISSUE THREAD

**Issue by deefrawley** [DeepVoyager253/FlowLauncherYTDownload#3]
Fresh and first install of the plugin. Others have this issue has they have posted in  the main Flow repo

```
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\Damien\AppData\Roaming\FlowLauncher\Logs\1.15.0\2023-07-05.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 19045.3086
IntPtr Length: 8
x64: True

Python Path: C:\Users\Damien\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 07/05/2023 19:22:38
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 68, in <module>
    YoutubeDownload()
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 62, in download_video
    video = youtube.streams.get_highest_resolution()
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 405, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 311, in get_throttling_function_code
    name = re.escape(get_throttling_function_name(js))
  File "C:\Users\Damien\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 296, in get_throttling_function_name
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 139
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 277
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by DrPMuster** [comment]
error message + log i hope this will help fix
Browser: Brave [Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)]
Log file:
[2023-08-13.txt](https://github.com/DeepVoyager253/FlowLauncherYTDownload/files/12329180/2023-08-13.txt)
____________________________________
Please open new issue in: https://github.com/Flow-Launcher/Flow.Launcher/issues
1. upload log file: C:\Users\Admin\AppData\Roaming\FlowLauncher\Logs\1.16.1\2023-08-13.txt
2. copy below exception message

Flow Launcher version: 1.16.1
OS Version: 17763.1577
IntPtr Length: 8
x64: True


Python Path: C:\Users\Admin\AppData\Local\Programs\Python\Python311\pythonw.exe
Node Path: 
Date: 08/13/2023 12:17:02
Exception:
System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 181, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 68, in <module>
    YoutubeDownload()
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\flowlauncher\FlowLauncher.py", line 33, in __init__
    results = request_method(*request_parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\main.py", line 62, in download_video
    video = youtube.streams.get_highest_resolution()
            ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
             ^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-v1.0.0-beta\lib\pytube\cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.<>c__DisplayClass19_0.<<ParseResults>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 136
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 286
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
