### ISSUE TITLE
Error, need help :)

### ISSUE THREAD

**Issue by jbuck95** [DeepVoyager253/FlowLauncherYTDownload#6]
I get the following error, maybe you can help: 

Log: [2024-01-07.txt](https://github.com/DeepVoyager253/FlowLauncherYTDownload/files/13852075/2024-01-07.txt)

> Flow Launcher version: 1.16.2
OS Version: 22621.2861
IntPtr Length: 8
x64: True

Python Path: C:\Users\Jan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\Jan\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 01/07/2024 04:00:01
Exception:
Youtube Downloader Exception: 
Websites: https://github.com/DeepVoyager253/FlowLauncherYTDownload
Author: LordOfTheEel; Eyal.Br
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException:   File "C:\Users\Jan\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-1.0.1\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

 ---> System.IO.InvalidDataException:   File "C:\Users\Jan\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-1.0.1\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Drigva** [comment]
1. Go to **\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-1.0.1**.
2. Right click Edit "**main.py**" file.
3. Replace both `f'explorer "{os.path.abspath(r".\Your Downloads")}"'` to `f'explorer "{os.path.abspath(os.path.expanduser("~/Downloads/Your Downloads"))}"'`
4. And both `video.download(output_path = "Your Downloads")` to `video.download(output_path=os.path.expanduser("~/Downloads/Your Downloads"))`
