### ISSUE TITLE
doesn't work for some reason

### ISSUE THREAD

**Issue by unprofessionalmemer** [DeepVoyager253/FlowLauncherYTDownload#9]
[log](https://github.com/DeepVoyager253/FlowLauncherYTDownload/files/14370837/2024-02-22.txt)
Flow Launcher version: 1.17.2
OS Version: 19045.4046
IntPtr Length: 8
x64: True

Python Path: C:\Users\total\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 02/22/2024 02:12:23
Exception:
Youtube Downloader Exception: 
Websites: https://github.com/DeepVoyager253/FlowLauncherYTDownload
Author: LordOfTheEel; Eyal.Br
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException:   File "C:\Users\total\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-1.0.1\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

 ---> System.IO.InvalidDataException:   File "C:\Users\total\AppData\Roaming\FlowLauncher\Plugins\Youtube Downloader-1.0.1\main.py", line 81
    os.system(f'explorer "{os.path.abspath(r".\Your Downloads")}"')
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 221
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 294
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by therealpigeonman** [comment]
im getting basically the same issue and it only happened after i updated
